# Generated by Django 4.0.1 on 2022-01-25 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Solo insertar catacteres.', regex='^[a-zA-Z]*$^')], verbose_name='Título completo del libro'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo insertar catacteres.', regex='^[a-zA-Z]*$^')], verbose_name='Nombre de la seccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo insertar catacteres.', regex='^[a-zA-Z]*$^')], verbose_name='Nombre del local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Solo insertar catacteres.', regex='^[a-zA-Z]*$^')]),
        ),
    ]
