# Generated by Django 4.0.1 on 2022-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0002_delete_empleado_alter_libro_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título completo del libro'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la seccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
