# Generated by Django 4.0.1 on 2022-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0004_rename_fecha_publicación_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.TextField(max_length=15),
        ),
    ]
