# Generated by Django 4.0.1 on 2022-01-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0005_alter_libro_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.IntegerField(verbose_name='Insertar solo año'),
        ),
    ]
