# Generated by Django 4.0.1 on 2022-01-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0006_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
